This is makeindex, version 2.15 [MiKTeX 2.9.6600 64-bit] (kpathsea + Thai support).
Scanning style file ./uw-ethesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file uw-ethesis.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (14 comparisons).
Generating output file uw-ethesis.acr....done (14 lines written, 0 warnings).
Output written in uw-ethesis.acr.
Transcript written in uw-ethesis.alg.
